### ISSUE TITLE
MacOS

### ISSUE THREAD

**Issue by erichter2018** [RandomNinjaAtk/Scripts#3]
Is there anything that needs to be altered in the MKV-Cleanup script for it to work on MacOS?  I'm getting "ERROR: No video files found for processing" error immediately.

**Comment by RandomNinjaAtk** [comment]
Hmm, idk, I've never tested it on MacOS. I don't personally have a Mac. These scripts did function when I wrote them, however, they were early testing for implementations in my various docker containers.

Edit, when these were written, they were used/tested on ubuntu based docker containers. The more evolved version of the script is this file from a container that I package:
https://github.com/RandomNinjaAtk/docker-sabnzbd-extended/blob/master/root/scripts/video-pp.bash

Hope that is helpful...
