### ISSUE TITLE
MKV Process script - Process Cloud Stored Files?

### ISSUE THREAD

**Issue by methanoid** [RandomNinjaAtk/Scripts#4]
Before the main Q, "UnkownAudioLanguage="eng"" is presumably a typo that needs adjustment in more than 1 place to "Unknown"

If your files are already on a cloud provider this gives you a problem to process them without downloading them and then doing on spinning rust. Could the script be amended to:

1) check if file needs some processing, if not do nothing
2) if processing needed, move file to new location (ie spinning rust) and do processing
3) move file back to original location

??

**Comment by RandomNinjaAtk** [comment]
These scripts have not been maintained or updated. Newer versions were directly included in various containers they were designed for, such as:
https://github.com/RandomNinjaAtk/docker-sabnzbd-extended

I regret to inform you that I won't be making any changes here, and archiving this repo to prevent future confusion.
